mode: cluster
server:
  port: 8081

discovery:
  etcd:
    prefix: '/discovery'
    endpoints: 
        - '127.0.0.1:2379'

actuator:
  databases:
    - id: '5662e9d0-9954-11ed-ac90-e6d8fb3d8925'
      driver-name: mysql
      url: 'root:123456@tcp(localhost:3306)/test?charset=utf8'

manager-center:
  store:
    etcd:
      prefix: '/prod'
      endpoints: 
        - '127.0.0.1:2379'
